
import java.awt.Color;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import javax.swing.JOptionPane;
import java.io.File;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author DELL
 */
public class EditorForm extends javax.swing.JFrame {

    /**
     * Creates new form EditorForm
     */
    public EditorForm() {
        initComponents();
        textareaBox.setEditable(true);
        radioTextBtn.setSelected(true);
        setTitle("Mini Text Editor");
        modeLabel.setText("Mode: WRITE");        
        modeLabel.setForeground(new Color(0,100,0));
        modeLabel.setFont(new Font("Arial", Font.BOLD, 14));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textareaBox = new javax.swing.JTextArea();
        textareaLabel = new javax.swing.JLabel();
        fileNameLabel = new javax.swing.JLabel();
        fileNameBox = new javax.swing.JTextField();
        fileTypeLabel = new javax.swing.JLabel();
        radioTextBtn = new javax.swing.JRadioButton();
        radioBinBtn = new javax.swing.JRadioButton();
        saveBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        openBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        modeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        textareaBox.setColumns(20);
        textareaBox.setRows(5);
        jScrollPane1.setViewportView(textareaBox);

        textareaLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textareaLabel.setText("Text");

        fileNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fileNameLabel.setText("File Name");

        fileTypeLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fileTypeLabel.setText("File Type");

        buttonGroup1.add(radioTextBtn);
        radioTextBtn.setText("Text");

        buttonGroup1.add(radioBinBtn);
        radioBinBtn.setText("Binary");
        radioBinBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBinBtnActionPerformed(evt);
            }
        });

        saveBtn.setBackground(new java.awt.Color(51, 255, 51));
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        editBtn.setBackground(new java.awt.Color(0, 153, 255));
        editBtn.setText("Edit");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        openBtn.setBackground(new java.awt.Color(255, 255, 51));
        openBtn.setText("Open");
        openBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openBtnActionPerformed(evt);
            }
        });

        clearBtn.setBackground(new java.awt.Color(255, 51, 51));
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        modeLabel.setForeground(new java.awt.Color(0, 102, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(fileNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fileNameBox, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioTextBtn)
                                    .addComponent(fileTypeLabel)
                                    .addComponent(radioBinBtn)
                                    .addComponent(openBtn)
                                    .addComponent(editBtn)
                                    .addComponent(clearBtn)
                                    .addComponent(saveBtn))))
                        .addGap(35, 35, 35)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textareaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(modeLabel)
                .addGap(112, 112, 112))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(textareaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(fileNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fileNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fileTypeLabel)
                        .addGap(18, 18, 18)
                        .addComponent(radioTextBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioBinBtn)
                        .addGap(47, 47, 47)
                        .addComponent(openBtn)
                        .addGap(18, 18, 18)
                        .addComponent(editBtn)
                        .addGap(18, 18, 18)
                        .addComponent(clearBtn)
                        .addGap(18, 18, 18)
                        .addComponent(saveBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(modeLabel)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioBinBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBinBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBinBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        String name = fileNameBox.getText();

        try {
            if (name.isEmpty()) {
                throw new Exception("Please Enter file name!");
            }

            File file;

            if (radioTextBtn.isSelected()) {
                file = new File(name + ".txt");
            } else {
                file = new File(name + ".bin");
            }

            if (file.exists()) {
                int choice = JOptionPane.showConfirmDialog(this, "File already exists! Do you want to Overwrite?");
                if (choice != 0) {
                    return;
                }
            }

            if (radioTextBtn.isSelected()) {
                FileWriter writer = new FileWriter(file);
                writer.write(textareaBox.getText());
                writer.close();
            } else {
                ObjectOutputStream out = new ObjectOutputStream(new FileOutputStream(file));
                out.writeObject(textareaBox.getText());
                out.close();
            }

            JOptionPane.showMessageDialog(this, "File saved successfully");

            textareaBox.setEditable(false);
            modeLabel.setText("Mode: READ"); 
            modeLabel.setForeground(Color.red);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        if (textareaBox.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please open file first!");
        } else {
            textareaBox.setEditable(true);
            modeLabel.setText("Mode: WRITE");        
            modeLabel.setForeground(new Color(0,100,0));
            
            JOptionPane.showMessageDialog(this, "Edit mode enabled now!");
        }
    }//GEN-LAST:event_editBtnActionPerformed

    private void openBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openBtnActionPerformed
        String name = fileNameBox.getText();

        try {
            if (name.isEmpty()) {
                throw new Exception("Please Enter file name!");
            }

            File file;

            if (radioTextBtn.isSelected()) {
                file = new File(name + ".txt");
            } else {
                file = new File(name + ".bin");
            }

            if (!file.exists()) {
                throw new Exception("File not found, Please enter a correct file name!");
            }

            textareaBox.setText("");

            if (radioTextBtn.isSelected()) {
                BufferedReader reader = new BufferedReader(new FileReader(file));
                String line;

                while ((line = reader.readLine()) != null) {
                    textareaBox.append(line + "\n");
                }

                reader.close();
            } else {
                ObjectInputStream in = new ObjectInputStream(new FileInputStream(file));
                String data = (String) in.readObject();
                textareaBox.setText(data);
                in.close();
            }

            JOptionPane.showMessageDialog(this, "File opened successfully!");

            textareaBox.setEditable(false);
            modeLabel.setText("Mode: READ");
            modeLabel.setForeground(Color.red);


        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_openBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        textareaBox.setText("");
        fileNameBox.setText("");
        buttonGroup1.clearSelection();
        radioTextBtn.setSelected(true);

        textareaBox.setEditable(true);
        modeLabel.setText("Mode: WRITE");        
        modeLabel.setForeground(new Color(0,100,0));

        JOptionPane.showMessageDialog(this, "Cleared successfully!");
    }//GEN-LAST:event_clearBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditorForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JTextField fileNameBox;
    private javax.swing.JLabel fileNameLabel;
    private javax.swing.JLabel fileTypeLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel modeLabel;
    private javax.swing.JButton openBtn;
    private javax.swing.JRadioButton radioBinBtn;
    private javax.swing.JRadioButton radioTextBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextArea textareaBox;
    private javax.swing.JLabel textareaLabel;
    // End of variables declaration//GEN-END:variables
}
